#pragma once


//---[ configs, extra ]------------------------------------------------------------------------------------------------------
#undef reg
#undef cbuffer
#undef row_major
#undef semantics
#undef SHARED_TYPE
#undef CONST
#undef AGE_WAVE_SIZE

#undef MAX_SELECTION_OUTLINE_THICKNESS
#undef MAX_BLOOM_MIP_COUNT
#undef MIN_BLOOM_MIP_PIXEL
#undef MAX_UV_COUNT
#undef MAX_RAY_HIT
#undef ENABLE_SHADER_DEBUG_ASSERT
#undef DEBUG_ASSERT_BUFFER_BYTE_SIZE

#undef AGE_SYSTEM_KIND_AO
#undef AGE_SYSTEM_KIND_AA
#undef AGE_SYSTEM_KIND_DDGI
#undef AGE_SYSTEM_KIND_GIBS
#undef AGE_SYSTEM_KIND_GIST
#undef AGE_SYSTEM_KIND_DEBUG_VIEW

#undef AGE_RASTER_MODE_OPAQUE
#undef AGE_RASTER_MODE_TRANSPARENT
#undef AGE_RASTER_MODE_MASK

#undef AGE_RASTER_OVERRIDE_KIND_NONE
#undef AGE_RASTER_OVERRIDE_KIND_FORCE_OPAQUE
#undef AGE_RASTER_OVERRIDE_KIND_FORCE_TRANSPARENT
#undef AGE_RASTER_OVERRIDE_KIND_FORCE_MASK

#undef AGE_SAMPLER_KIND_LINEAR_WRAP
#undef AGE_SAMPLER_KIND_LINEAR_CLAMP
#undef AGE_SAMPLER_KIND_LINEAR_MIRROR
#undef AGE_SAMPLER_KIND_POINT_WRAP
#undef AGE_SAMPLER_KIND_POINT_CLAMP
#undef AGE_SAMPLER_KIND_POINT_MIRROR

#undef AGE_MATERIAL_SHADING_MODEL_PBR_DEFAULT
#undef AGE_MATERIAL_SHADING_MODEL_PBR_UNLIT

#undef AGE_RT_ALPHA_TEST_OVERRIDE_KIND_NONE
#undef AGE_RT_ALPHA_TEST_OVERRIDE_KIND_OPAQUE
#undef AGE_RT_ALPHA_TEST_OVERRIDE_KIND_BLEND
#undef AGE_RT_ALPHA_TEST_OVERRIDE_KIND_MASK

#undef AGE_RT_ALPHA_TEST_MODE_OPAQUE
#undef AGE_RT_ALPHA_TEST_MODE_BLEND
#undef AGE_RT_ALPHA_TEST_MODE_MASK

//---[ sort ]------------------------------------------------------------------------------------------------------
#undef SORT_THREAD_COUNT
#undef SORT_ELEMENT_COUNT_PER_THREAD
#undef MAX_SORT_COUNT
#undef SORT_BLOCK_SIZE
#undef SORT_BLOCK_COUNT
#undef SORT_GROUP_COUNT

#undef SORT_BLOCK_COUNT_PER_GROUP
#undef SORT_BIN_BIT_WIDTH
#undef SORT_BIN_COUNT
#undef SORT_HISTOGRAM_TABLE_SIZE

//---[ light ]------------------------------------------------------------------------------------------------------
#undef MAX_LIGHT_COUNT
#undef MAX_ENV_LIGHT
#undef MAX_DIRECTIONAL_LIGHT_COUNT
#undef MAX_SHADOW_LIGHT_COUNT

#undef LIGHT_BIN_INIT_THREAD_COUNT
#undef LIGHT_CULL_THREAD_COUNT
#undef LIGHT_ZBIN_THREAD_COUNT
#undef LIGHT_BITMASK_UINT32_COUNT
#undef X_SLICE_COUNT
#undef Y_SLICE_COUNT
#undef Z_SLICE_COUNT
#undef LIGHT_AXIS_SLICE_MAX
#undef LIGHT_BIN_ENTRY_X_OFFSET
#undef LIGHT_BIN_ENTRY_Y_OFFSET
#undef LIGHT_BIN_ENTRY_Z_OFFSET
#undef LIGHT_BIN_MASK_X_OFFSET
#undef LIGHT_BIN_MASK_Y_OFFSET
#undef LIGHT_BIN_MASK_Z_OFFSET
#undef LIGHT_BIN_BUFFER_SIZE
#undef LIGHT_KIND_DIRECTIONAL
#undef LIGHT_KIND_POINT
#undef LIGHT_KIND_SPOT
#undef LIGHT_KIND_AREA
#undef LIGHT_KIND_VOLUMN

//---[ object, meshlet ]------------------------------------------------------------------------------------------------------
#undef MAX_MESHLET_RENDER_DATA_COUNT
#undef MAX_INSTANCE_SUBMESH_COUNT
#undef MAX_OBJECT_DATA_COUNT
#undef VERTEX_KIND_P_UV0
#undef VERTEX_KIND_PN_UV0
#undef VERTEX_KIND_PNT_UV0
#undef VERTEX_KIND_P_UV1
#undef VERTEX_KIND_PN_UV1
#undef VERTEX_KIND_PNT_UV1
#undef VERTEX_KIND_P_UV2
#undef VERTEX_KIND_PN_UV2
#undef VERTEX_KIND_PNT_UV2
#undef VERTEX_KIND_P_UV3
#undef VERTEX_KIND_PN_UV3
#undef VERTEX_KIND_PNT_UV3

#undef VERTEX_SIZE_P_UV0
#undef VERTEX_SIZE_PN_UV0
#undef VERTEX_SIZE_PNT_UV0
#undef VERTEX_SIZE_P_UV1
#undef VERTEX_SIZE_PN_UV1
#undef VERTEX_SIZE_PNT_UV1
#undef VERTEX_SIZE_P_UV2
#undef VERTEX_SIZE_PN_UV2
#undef VERTEX_SIZE_PNT_UV2
#undef VERTEX_SIZE_P_UV3
#undef VERTEX_SIZE_PN_UV3
#undef VERTEX_SIZE_PNT_UV3

//---[ static buffer offset ]------------------------------------------------------------------------------------------------------
#undef INSTANCE_SUBMESH_MATERIAL_OFFSET
#undef OBJECT_ID_BUFFER_OFFSET
#undef OBJECT_PREV_DATA_OFFSET
#undef OBJECT_DATA_OFFSET
#undef OBJECT_RENDER_DATA_OFFSET
#undef DIRECTIONAL_LIGHT_OFFSET
#undef UNIFIED_LIGHT_OFFSET
#undef BLOOM_OFFSET
#undef DDGI_DATA_OFFSET
#undef GIBS_DATA_OFFSET
#undef GIBS_LUT_DATA_OFFSET
#undef GIST_DATA_OFFSET
#undef GIST_LUT_DATA_OFFSET
#undef AO_DATA_OFFSET
#undef SEGMENT_DATA_OFFSET
#undef AA_DATA_OFFSET
#undef STATIC_BUFFER_SIZE

//---[ scratch buffer offset ]------------------------------------------------------------------------------------------------------
#undef SCRATCH_SORT_BUFFER_OFFSET
#undef SORT_KEYS_OFFSET
#undef SORT_KEYS_ALT_OFFSET
#undef SORT_VALUES_OFFSET
#undef SORT_VALUES_ALT_OFFSET
#undef SORT_HISTOGRAM_OFFSET
#undef SORT_BIN_COUNT_OFFSET
#undef SCRATCH_BUFFER_TOTAL_SIZE


//---[ rt ]------------------------------------------------------------------------------------------------------
#undef RT_MASK_NONE
#undef RT_MASK_OPAQUE
#undef RT_MASK_TRANSPARENT
#undef RT_MASK_OMM
#undef RT_MASK_DEBUG
#undef RT_MASK_ALWAYS_ON_TOP
#undef RT_MASK_ALL


//---[ ui ]------------------------------------------------------------------------------------------------------
#undef UI_SPACE_MODE_SCREEN
#undef UI_SPACE_MODE_WORLD
#undef UI_SPACE_MODE_WORLD_ALWAYS_ON_TOP
#undef UI_SPACE_MODE_WORLD_BILLBOARD

#undef UI_BRUSH_KIND_COLOR


//---[ material ]------------------------------------------------------------------------------------------------------

//---[ ddgi ]------------------------------------------------------------------------------------------------------

#undef DDGI_BORDER

// do not change
#undef DDGI_IRRADIANCE_RESOLUTION
#undef DDGI_VISIBILITY_RESOLUTION
#undef DDGI_IRRADIANCE_TILE_SIZE
#undef DDGI_VISIBILITY_TILE_SIZE

#undef DDGI_UPDATE_PROBE_STATE_PROBE_PER_THREAD
#undef DDGI_UPDATE_PROBE_STATE_THREAD_PER_GROUP	   // wave_count

#undef DDGI_PROBE_STATE_OFF
#undef DDGI_PROBE_STATE_ACTIVE
#undef DDGI_PROBE_STATE_SLEEP
#undef DDGI_PROBE_STATE_NEW_BORN
#undef DDGI_PROBE_STATE_INSIDE_WALL

#undef DDGI_PROBE_RAY_COUNT_NEW_BORN

#undef DDGI_RAY_BUDGET
#undef DDGI_MSME_SHORT_WINDOW_BLEND

#undef DDGI_IRRADIANCE_ENERGY_CONSERVATION

#undef DDGI_VISIBILITY_SHARPNESS
#undef DDGI_VISIBILITY_BLEND_FACTOR

#undef DDGI_PROBE_WEIGHT_SCALE

#undef DDGI_DEBUG_FLAGS_RENDER_PROBE_IN_HOLE
#undef DDGI_DEBUG_FLAGS_RENDER_IRRADIANCE
#undef DDGI_DEBUG_FLAGS_RENDER_VISIBILITY
#undef DDGI_DEBUG_FLAGS_RENDER_FRONT_BACK
#undef DDGI_DEBUG_FLAGS_RENDER_LEVEL
#undef DDGI_DEBUG_FLAGS_RENDER_WEIGHT_SUM
#undef DDGI_DEBUG_FLAGS_RENDER_RAY_COUNT
#undef DDGI_DEBUG_FLAGS_RENDER_STATE
#undef DDGI_DEBUG_FLAGS_RENDER_MSME
#undef DDGI_DEBUG_FLAGS_RENDER_RAY_FACTOR
#undef DDGI_DEBUG_FLAGS_RENDER_PROBE

#undef DDGI_PREFIX_THREAD_COUNT
#undef DDGI_PREFIX_ELEMENT_PER_THREAD
#undef DDGI_PREFIX_ELEMENT_PER_GROUP

#undef DDGI_TRACE_THREAD_PER_GROUP

#undef DDGI_PROBE_MAX

#undef DDGI_NORMAL_BIAS
#undef DDGI_VIEW_BIAS

#undef DDGI_MEAN_SQ_THRESHOLD
#undef DDGI_NORMAL_BLEND


//---[ gibs ]------------------------------------------------------------------------------------------------------
#undef GIBS_ATLAS_TILE_SIZE
#undef GIBS_MAX_SURFEL_COUNT
#undef GIBS_MIN_RAY_PER_SURFEL
#undef GIBS_MAX_RAY_PER_SURFEL

#undef GIBS_SURFEL_OUTER_RADIUS_FACTOR

#undef GIBS_TILE_PREFIX_TPG
#undef GIBS_TILE_PREFIX_EPT
#undef GIBS_TILE_PREFIX_EPG

#undef GIBS_CELL_PREFIX_TPG
#undef GIBS_CELL_PREFIX_EPT
#undef GIBS_CELL_PREFIX_EPG

#undef GIBS_RAY_REDUCE_TPG
#undef GIBS_RAY_REDUCE_EPT
#undef GIBS_RAY_REDUCE_EPG

#undef GIBS_MAX_OUTER_LAYER_COUNT

#undef GIBS_TILE_SURFEL_SPAWN_COVERAGE
#undef GIBS_TILE_SURFEL_KILL_COVERAGE

#undef GIBS_NEAR_CONTRIBUTION_TRUST_BIAS

#undef GIBS_CELL_SURFEL_SPAWN_COVERAGE_NEAR
#undef GIBS_CELL_SURFEL_KILL_COVERAGE_NEAR

// 1.f : full hemisphere cover
#undef GIBS_CELL_SURFEL_SPAWN_COVERAGE_FAR
#undef GIBS_CELL_SURFEL_KILL_COVERAGE_FAR


#undef GIBS_SPAWN_PROB_FACTOR
#undef GIBS_KILL_PROB_FACTOR

#undef GIBS_RADIANCE_CACHE_DELAY
#undef GIBS_MSME_SHORT_WINDOW_BLEND
#undef GIBS_MIN_LUMINANCE
#undef GIBS_MIN_LUMINANCE_FOR_RAY_GUIDANCE

#undef GIBS_GI_RESOLVE_BLOCK_SIZE
#undef GIBS_GI_RESOLVE_BLOCK_DIM
#undef GIBS_GI_RESOLVE_SAMPLE_PER_BLOCK
#undef GIBS_GI_RESOLVE_TILE_SIZE
#undef GIBS_GI_RESOLVE_SAMPLE_PER_TILE

#undef GIBS_DEBUG_FLAGS_NONE
#undef GIBS_DEBUG_FLAGS_FREEZE_SPAWN_KILL
#undef GIBS_DEBUG_FLAGS_RENDER_TILE
#undef GIBS_DEBUG_FLAGS_RENDER_CELL
#undef GIBS_DEBUG_FLAGS_RENDER_TILE_SURFELS
#undef GIBS_DEBUG_FLAGS_RENDER_CELL_SURFELS
#undef GIBS_DEBUG_FLAGS_RENDER_ID_HASH
#undef GIBS_DEBUG_FLAGS_RENDER_RADIANCE
#undef GIBS_DEBUG_FLAGS_RENDER_IRRADIANCE
#undef GIBS_DEBUG_FLAGS_RENDER_NORMAL
#undef GIBS_DEBUG_FLAGS_RENDER_VISIBILITY
#undef GIBS_DEBUG_FLAGS_RENDER_NEAR_COVERAGE
#undef GIBS_DEBUG_FLAGS_RENDER_FAR_COVERAGE
#undef GIBS_DEBUG_FLAGS_RENDER_RAY_COUNT
#undef GIBS_DEBUG_FLAGS_RENDER_AGE

//---[ gist ]------------------------------------------------------------------------------------------------------

#undef GIST_ATLAS_TILE_SIZE
#undef GIST_MAX_OUTER_LAYER_COUNT
#undef GIST_MAX_CELL_SURFEL_COUNT
#undef GIST_MSME_SHORT_WINDOW_BLEND
#undef GIST_MSME_INCONSISTENCY_BLEND
#undef GIST_CELL_SURFEL_FRAME_SINCE_REF_TO_KILL
#undef GIST_CELL_SURFEL_NEW_BORN_DELAY
#undef GIST_CELL_SURFEL_RADIUS_RATIO
#undef GIST_NEAR_CONTRIBUTION_TRUST_BIAS
#undef GIST_CELL_SURFEL_SPAWN_COVERAGE_NEAR
#undef GIST_CELL_SURFEL_KILL_COVERAGE_NEAR
#undef GIST_CELL_SURFEL_SPAWN_COVERAGE_FAR
#undef GIST_CELL_SURFEL_KILL_COVERAGE_FAR
#undef GIST_CELL_SURFEL_SPAWN_PROB_FACTOR
#undef GIST_CELL_SURFEL_KILL_PROB_FACTOR
#undef GIST_GI_RESOLVE_MAX_AGE
#undef GIST_GI_RESOLVE_BLOCK_SIZE
#undef GIST_GENERAL_EPT
#undef GIST_GENERAL_TPG
#undef GIST_GENERAL_EPG
#undef GIST_MIN_LUMINANCE
#undef GIST_MIN_LUMINANCE_SUM_FOR_RAY_GUIDANCE
#undef GIST_PX_LUMINANCE_TILE_SIZE
#undef GIST_PX_RAY_GUIDE_PROB
#undef GIST_ADAPTIVE_RAY_TYPE_NEW_BORN
#undef GIST_ADAPTIVE_RAY_TYPE_SPECULAR
#undef GIST_ADAPTIVE_RAY_TYPE_VARIANCE
#undef GIST_ADAPTIVE_RAY_TYPE_COUNT
#undef GIST_ADAPTIVE_RAY_SPECULAR_ROUGHNESS_MAX
#undef GIST_ADAPTIVE_RAY_TILE_SIZE
#undef GIST_DEBUG_FLAGS_FREEZE_SURFEL_SPAWN
#undef GIST_DEBUG_FLAGS_FREEZE_SURFEL_KILL
#undef GIST_DEBUG_FLAGS_FREEZE_SURFEL_RADIUS

//---[ segment and transparent ]------------------------------------------------------------------------------------------------------
#undef SEGMENT_TILE_SIZE

//---[ ao ]------------------------------------------------------------------------------------------------------
#undef AO_DEBUG_FLAGS_RENDER_AO_BUFFER

//---[ debug view ]------------------------------------------------------------------------------------------------------
#undef DEBUG_VIEW_SLOT_COUNT_MAX

//---[ debug assert ]------------------------------------------------------------------------------------------------------

#undef DEBUG_ARG_TYPE_UINT64
#undef DEBUG_ARG_TYPE_UINT32

#undef DEBUG_ARG_TYPE_INT64
#undef DEBUG_ARG_TYPE_INT32

#undef DEBUG_ARG_TYPE_FLOAT

#undef DEBUG_ARG_TYPE_INT32_2
#undef DEBUG_ARG_TYPE_INT32_3
#undef DEBUG_ARG_TYPE_INT32_4

#undef DEBUG_ARG_TYPE_UINT32_2
#undef DEBUG_ARG_TYPE_UINT32_3
#undef DEBUG_ARG_TYPE_UINT32_4

#undef DEBUG_ARG_TYPE_FLOAT2
#undef DEBUG_ARG_TYPE_FLOAT3
#undef DEBUG_ARG_TYPE_FLOAT4

#undef DEBUG_ARG_TYPE_FLOAT2X2
#undef DEBUG_ARG_TYPE_FLOAT2X3
#undef DEBUG_ARG_TYPE_FLOAT2X4

#undef DEBUG_ARG_TYPE_FLOAT3X2
#undef DEBUG_ARG_TYPE_FLOAT3X3
#undef DEBUG_ARG_TYPE_FLOAT3X4

#undef DEBUG_ARG_TYPE_FLOAT4X2
#undef DEBUG_ARG_TYPE_FLOAT4X3
#undef DEBUG_ARG_TYPE_FLOAT4X4

#undef DEBUG_ARG_TYPE_STRING
#undef DEBUG_ARG_TYPE_SRC_LINE
